[package]
name = "ChronoTrack"
version = "0.0.1"
edition = "2021"
license = "MIT"
build = "build.rs"
description = "Tracking Timecards Made Easy"

[dependencies]
slint = "1.10"

[build-dependencies]
slint-build = "1.10"
